const { ipcRenderer } = require('electron');
const HOME='https://ogatiertech.github.io/AitherWeb/';
const tabs=[{url:HOME,title:'Aither Web',history:[]}];let active=0;
const $=id=>document.getElementById(id);const views=$('views');
function searchOrUrl(v){v=v.trim();if(!v)return HOME;if(/^(https?:\/\/|file:|about:)/i.test(v))return v;if(v.includes('.')&&!v.includes(' '))return'https://'+v;return'https://www.google.com/search?q='+encodeURIComponent(v)}
function renderTabs(){document.querySelectorAll('.tab').forEach((x,i)=>x.classList.toggle('active',i===active));document.querySelector('.tab-title').textContent=tabs[active].title||'New Tab'}
function createTab(url=HOME){tabs.push({url,title:'New Tab',history:[]});active=tabs.length-1;load(url);renderTabs()}
function load(raw,push=true){const t=tabs[active],url=searchOrUrl(raw);if(push&&t.url&&t.url!==url)t.history.push(t.url);t.url=url;const old=views.querySelector('webview');if(old)old.remove();const w=document.createElement('webview');w.src=url;w.allowpopups=true;w.setAttribute('partition','persist:aither');views.appendChild(w);w.addEventListener('did-start-loading',()=>{$('url').value=w.getURL()||url});w.addEventListener('did-navigate',()=>{t.url=w.getURL();$('url').value=t.url;updateTitle(w.getTitle())});w.addEventListener('page-title-updated',e=>updateTitle(e.title));w.addEventListener('did-fail-load',()=>updateTitle('Page unavailable'));renderTabs()}
function updateTitle(title){tabs[active].title=title||'Aither Browser';renderTabs()}
$('url').addEventListener('keydown',e=>{if(e.key==='Enter')load(e.target.value)});$('clear').onclick=()=>{$('url').value='';$('url').focus()};$('reload').onclick=()=>views.querySelector('webview')?.reload();$('home').onclick=()=>load(HOME);$('back').onclick=()=>{const w=views.querySelector('webview');if(w?.canGoBack())w.goBack();else{const t=tabs[active];if(t.history.length)load(t.history.pop(),false)}};$('forward').onclick=()=>views.querySelector('webview')?.goForward();$('newTab').onclick=()=>createTab();$('star').onclick=()=>{localStorage.setItem('aither-last-bookmark',tabs[active].url);$('star').textContent='★';setTimeout(()=>$('star').textContent='☆',900)};$('menu').onclick=()=>alert('Aither Browser\n\nGoogle search\nTabs\nBack / Forward\nReload\nBookmarks\nAither Web home');ipcRenderer.on('open-url',(_e,url)=>load(url));load(HOME,false);
