const {ipcRenderer}=require('electron');const HOME='https://ogatiertech.github.io/AitherWeb/';const tabs=[{url:HOME,title:'Aither Web',history:[]}];let active=0;const $=id=>document.getElementById(id),views=$('views');
function searchOrUrl(v){v=v.trim();if(!v)return HOME;if(/^(https?:\/\/|file:|about:)/i.test(v))return v;if(v.includes('.')&&!v.includes(' '))return'https://'+v;return'https://www.google.com/search?q='+encodeURIComponent(v)}
function renderTabs(){document.querySelectorAll('.tab').forEach((x,i)=>x.classList.toggle('active',i===active));document.querySelectorAll('.tab-title')[active].textContent=tabs[active].title||'New Tab';document.querySelectorAll('.tab').forEach((x,i)=>x.onclick=e=>{if(!e.target.classList.contains('tab-close')){active=i;showActive()}});document.querySelectorAll('.tab-close').forEach((x,i)=>x.onclick=e=>{e.stopPropagation();closeTab(i)})}
function createTab(url=HOME){tabs.push({url,title:'New Tab',history:[]});active=tabs.length-1;load(url,false);renderTabs()}
function closeTab(i){if(tabs.length===1)return;tabs.splice(i,1);if(active>=tabs.length)active=tabs.length-1;showActive()}
function showActive(){const w=views.querySelector('webview');if(w)w.remove();load(tabs[active].url,false);renderTabs()}
function load(raw,push=true){const t=tabs[active],url=searchOrUrl(raw);if(push&&t.url&&t.url!==url)t.history.push(t.url);t.url=url;const old=views.querySelector('webview');if(old)old.remove();const w=document.createElement('webview');w.src=url;w.allowpopups=true;w.setAttribute('partition','persist:aither');views.appendChild(w);w.addEventListener('did-navigate',()=>{t.url=w.getURL();$('url').value=t.url;updateTitle(w.getTitle())});w.addEventListener('did-navigate-in-page',()=>{t.url=w.getURL();$('url').value=t.url});w.addEventListener('page-title-updated',e=>updateTitle(e.title));w.addEventListener('did-start-loading',()=>{$('reload').textContent='×'});w.addEventListener('did-stop-loading',()=>{$('reload').textContent='↻'});w.addEventListener('did-fail-load',()=>updateTitle('Page unavailable'));$('url').value=url;renderTabs()}
function updateTitle(title){tabs[active].title=title||'Aither Browser';renderTabs()}
function bookmark(){localStorage.setItem('aither-bookmarks',JSON.stringify([...JSON.parse(localStorage.getItem('aither-bookmarks')||'[]'),{name:tabs[active].title,url:tabs[active].url,icon:(tabs[active].title||'A')[0].toUpperCase()}]));$('star').textContent='★';setTimeout(()=>$('star').textContent='☆',800)}
$('url').onkeydown=e=>{if(e.key==='Enter')load(e.target.value)};$('clear').onclick=()=>{$('url').value='';$('url').focus()};$('reload').onclick=()=>{const w=views.querySelector('webview');if(w){if($('reload').textContent==='×')w.stop();else w.reload()}};$('home').onclick=()=>load(HOME);$('back').onclick=()=>views.querySelector('webview')?.goBack();$('forward').onclick=()=>views.querySelector('webview')?.goForward();$('newTab').onclick=()=>createTab();$('star').onclick=bookmark;$('menu').onclick=()=>{$('menuPanel').classList.toggle('hidden')};document.querySelectorAll('#menuPanel button').forEach(b=>b.onclick=()=>{const a=b.dataset.action;$('menuPanel').classList.add('hidden');if(a==='new')createTab();if(a==='bookmark')bookmark();if(a==='history')createTab(HOME+'#history');if(a==='home')load(HOME);if(a==='devtools')views.querySelector('webview')?.openDevTools()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='l'){e.preventDefault();$('url').focus();$('url').select()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='t'){e.preventDefault();createTab()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='w'){e.preventDefault();closeTab(active)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();bookmark()}});document.addEventListener('click',e=>{if(!$('menuPanel').contains(e.target)&&e.target!==$('menu'))$('menuPanel').classList.add('hidden')});ipcRenderer.on('open-url',(_e,url)=>load(url));load(HOME,false);