(()=>{
const API=()=>localStorage.getItem('aither-backend-url')||'https://aither-backend.onrender.com';
const escA=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`#aitherAccountButton{width:36px;height:36px;border:0;border-radius:50%;background:transparent;color:#bdc1c6;font-size:18px;flex:0 0 36px}#aitherAccountButton:hover{background:#3c4043}.account-modal{position:fixed;inset:0;z-index:90;background:#0009;backdrop-filter:blur(6px);display:grid;place-items:center;padding:16px}.account-card{width:min(440px,100%);background:#292a2d;color:#e8eaed;border:1px solid #5f6368;border-radius:18px;padding:22px;box-shadow:0 20px 70px #000}.account-head{display:flex;justify-content:space-between;align-items:center}.account-head h2{margin:0;font-size:25px;font-weight:500}.account-close{width:40px;height:40px;border:0;border-radius:50%;background:transparent;color:#bdc1c6;font-size:22px}.account-kicker{font-size:10px;letter-spacing:.16em;color:#8ab4f8;font-weight:800}.account-form{display:grid;gap:12px;margin-top:18px}.account-form label{display:grid;gap:6px;font-size:12px;color:#bdc1c6}.account-form input{width:100%;min-height:45px;border:1px solid #5f6368;border-radius:9px;background:#303134;color:#fff;padding:10px 12px;font-size:15px;outline:0}.account-form input:focus{border-color:#8ab4f8}.account-submit{min-height:46px;border:0;border-radius:9px;background:#8ab4f8;color:#202124;font-weight:700;font-size:14px}.account-switch{border:0;background:transparent;color:#8ab4f8;padding:10px;font-size:13px}.account-status{min-height:20px;margin-top:10px;font-size:12px;color:#9aa0a6;line-height:1.4}.account-user{display:grid;gap:8px;margin-top:18px;padding:15px;border:1px solid #3c4043;border-radius:12px;background:#303134}.account-user strong{font-size:18px}.account-user small{color:#9aa0a6}.account-actions{display:grid;gap:8px;margin-top:14px}.account-secondary{min-height:44px;border:1px solid #5f6368;border-radius:8px;background:#303134;color:#e8eaed;font-weight:600}.account-api{margin-top:18px;padding-top:14px;border-top:1px solid #3c4043}.account-api summary{cursor:pointer;color:#9aa0a6;font-size:12px}.account-api input{margin-top:8px;width:100%;min-height:40px;border:1px solid #5f6368;border-radius:8px;background:#303134;color:#fff;padding:8px}.light .account-card{background:#fff;color:#202124}.light .account-form input,.light .account-user,.light .account-secondary,.light .account-api input{background:#f1f3f4;color:#202124;border-color:#dadce0}`;document.head.appendChild(css);
const button=document.createElement('button');button.id='aitherAccountButton';button.type='button';button.setAttribute('aria-label','Account');button.title='Aither Account';button.textContent='●';document.querySelector('.toolbar')?.appendChild(button);
const modal=document.createElement('div');modal.className='account-modal hidden';modal.innerHTML=`<div class="account-card"><div class="account-head"><div><div class="account-kicker">AITHER ACCOUNT</div><h2 id="accountTitle">Create account</h2></div><button class="account-close" type="button">×</button></div><div id="accountBody"></div><div class="account-api"><details><summary>Backend connection</summary><input id="accountApi" placeholder="https://your-aither-backend.example"></details></div></div>`;document.body.appendChild(modal);
const body=modal.querySelector('#accountBody'),apiInput=modal.querySelector('#accountApi');apiInput.value=API();let mode='register',current=null;
function render(){if(current){body.innerHTML=`<div class="account-user"><strong>${escA(current.name)}</strong><small>${escA(current.email)}</small><small>${current.email_verified?'Email verified':'Email not verified'}</small></div><div class="account-actions"><button class="account-secondary" id="accountLogout" type="button">Log out</button></div>`;body.querySelector('#accountLogout').onclick=logout;return}body.innerHTML=`<form class="account-form" id="accountForm">${mode==='register'?'<label>Name<input name="name" autocomplete="name" required maxlength="80"></label>':''}<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="${mode==='register'?'new-password':'current-password'}" minlength="8" required></label><button class="account-submit" type="submit">${mode==='register'?'Create account':'Sign in'}</button></form><div class="account-status" id="accountStatus"></div><button class="account-switch" id="accountSwitch" type="button">${mode==='register'?'Already have an account? Sign in':'Need an account? Create one'}</button>`;body.querySelector('#accountForm').addEventListener('submit',submit);body.querySelector('#accountSwitch').onclick=()=>{mode=mode==='register'?'login':'register';render()}}
async function request(path,options={}){const r=await fetch(API()+path,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw Error(data.detail||'AitherBackend request failed.');return data}
async function submit(e){e.preventDefault();const form=e.currentTarget,status=body.querySelector('#accountStatus'),data=Object.fromEntries(new FormData(form));if(mode==='register'&&String(data.password).length<8){status.textContent='Password must be at least 8 characters.';return}status.textContent='Connecting to AitherBackend…';form.querySelector('button').disabled=true;try{const result=await request(mode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(data)});current=result.user;status.textContent='Account connected.';render();if(window.toast)toast(mode==='register'?'Aither account created':'Signed in to Aither');}catch(err){status.textContent=err.message;form.querySelector('button').disabled=false}}
async function session(){try{const r=await request('/api/auth/session');current=r.authenticated?r.user:null;render()}catch{current=null;render()}}
async function logout(){try{await request('/api/auth/logout',{method:'POST'})}catch{}current=null;render();if(window.toast)toast('Logged out')}
apiInput.addEventListener('change',()=>{let v=apiInput.value.trim().replace(/\/$/,'');if(v){localStorage.setItem('aither-backend-url',v);session()}});
button.onclick=()=>{modal.classList.remove('hidden');session();setTimeout(()=>body.querySelector('input')?.focus(),50)};modal.querySelector('.account-close').onclick=()=>modal.classList.add('hidden');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.add('hidden')});render();session();
})();