/* Aither Web downloads UI */
(()=>{
 const KEY='aither-downloads';const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
 const style=document.createElement('style');style.textContent=`.downloads-panel{position:fixed;z-index:90;right:10px;top:calc(98px + env(safe-area-inset-top));width:min(430px,calc(100vw - 20px));max-height:min(70dvh,620px);overflow:auto;background:#292a2d;border:1px solid #5f6368;border-radius:14px;box-shadow:0 18px 50px #000b;padding:14px}.downloads-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.downloads-head h2{font-size:18px;margin:0}.downloads-close{border:0;background:transparent;color:#bdc1c6;font-size:22px;width:38px;height:38px;border-radius:50%}.download-item{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:center;padding:11px 4px;border-bottom:1px solid #3c4043}.download-icon{width:38px;height:38px;border-radius:9px;display:grid;place-items:center;background:#303134;color:#8ab4f8;font-weight:700}.download-name{font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.download-url{font-size:11px;color:#9aa0a6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.download-actions{display:flex;gap:4px}.download-actions button{border:1px solid #5f6368;background:#303134;color:#e8eaed;border-radius:7px;min-width:34px;min-height:34px}.download-empty{padding:28px 12px;text-align:center;color:#9aa0a6}.download-toolbar{display:flex;gap:7px;margin-top:10px}.download-toolbar button{flex:1;min-height:40px;border:1px solid #5f6368;border-radius:8px;background:#303134;color:#e8eaed}@media(max-width:700px){.downloads-panel{inset:0;width:auto;max-height:none;border:0;border-radius:0;padding:calc(12px + env(safe-area-inset-top)) 12px calc(12px + env(safe-area-inset-bottom));background:#202124}.download-item{padding:13px 2px}.download-actions button{min-width:40px;min-height:40px}}body.light .downloads-panel{background:#fff;border-color:#dadce0}body.light .download-item{border-color:#dadce0}body.light .download-icon,body.light .download-toolbar button,body.light .download-actions button{background:#f1f3f4;color:#202124;border-color:#dadce0}`;document.head.appendChild(style);
 const button=document.createElement('button');button.className='chrome-btn';button.id='downloadsButton';button.type='button';button.setAttribute('aria-label','Downloads');button.textContent='↓';document.querySelector('.toolbar')?.insertBefore(button,document.getElementById('star'));
 const panel=document.createElement('section');panel.className='downloads-panel hidden';panel.setAttribute('aria-label','Downloads');panel.innerHTML='<div class="downloads-head"><div><h2>Downloads</h2></div><button class="downloads-close" type="button" aria-label="Close downloads">×</button></div><div class="downloads-list"></div><div class="download-toolbar"><button type="button" data-clear>Clear downloads</button></div>';document.body.appendChild(panel);const list=panel.querySelector('.downloads-list');
 const esc=s=>String(s||'');function render(){const data=get();list.innerHTML='';if(!data.length){list.innerHTML='<div class="download-empty">No downloads yet.</div>';return}data.forEach((d,i)=>{const row=document.createElement('div');row.className='download-item';row.innerHTML='<div class="download-icon">↓</div><div><div class="download-name"></div><div class="download-url"></div></div><div class="download-actions"><button type="button" data-open>Open</button><button type="button" data-remove aria-label="Remove download">×</button></div>';row.querySelector('.download-name').textContent=esc(d.name||'Downloaded file');row.querySelector('.download-url').textContent=esc(d.url);row.querySelector('[data-open]').onclick=()=>location.href=d.url;row.querySelector('[data-remove]').onclick=()=>{const x=get();x.splice(i,1);save(x);render()};list.appendChild(row)})}
 function add(url,name){if(!/^https?:/i.test(url))return;const x=get().filter(d=>d.url!==url);x.unshift({url,name:name||new URL(url).hostname,date:Date.now()});save(x.slice(0,50));render()}
 button.onclick=()=>{render();panel.classList.toggle('hidden')};panel.querySelector('.downloads-close').onclick=()=>panel.classList.add('hidden');panel.querySelector('[data-clear]').onclick=()=>{save([]);render()};document.addEventListener('click',e=>{if(!panel.contains(e.target)&&e.target!==button)panel.classList.add('hidden')});
 window.aitherAddDownload=add;window.addEventListener('beforeunload',()=>{});render();
})();