/* Aither Web mobile tab switcher */
(()=>{
  const isMobile=()=>matchMedia('(max-width:700px)').matches;
  const tabsEl=()=>document.getElementById('chromeTabs');
  const page=document.getElementById('page');
  const style=document.createElement('style');
  style.textContent=`
  #mobileTabButton{display:none}.mobile-tabs-sheet{position:fixed;inset:0;z-index:100;background:rgba(15,16,18,.96);backdrop-filter:blur(18px);padding:calc(12px + env(safe-area-inset-top)) 14px calc(14px + env(safe-area-inset-bottom));overflow:auto}.mobile-tabs-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:16px}.mobile-tabs-head h2{margin:0;font-size:20px}.mobile-tabs-close{border:0;background:#303134;color:#fff;border-radius:50%;width:42px;height:42px;font-size:25px}.mobile-tabs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.mobile-tab-card{position:relative;min-height:150px;border:1px solid #3c4043;border-radius:16px;background:#202124;overflow:hidden;text-align:left;box-shadow:0 8px 24px #0004}.mobile-tab-card.active{border-color:#8ab4f8;box-shadow:0 0 0 2px #8ab4f833}.mobile-tab-preview{height:88px;background:linear-gradient(135deg,#292a2d,#17181a);display:flex;align-items:center;justify-content:center;color:#9aa0a6;font-size:28px}.mobile-tab-info{padding:10px 40px 10px 12px}.mobile-tab-title{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:600}.mobile-tab-host{display:block;color:#9aa0a6;font-size:11px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mobile-tab-x{position:absolute;right:8px;bottom:8px;border:0;background:#303134;color:#fff;border-radius:50%;width:32px;height:32px;font-size:19px}.mobile-tabs-new{width:100%;margin:14px 0 4px;min-height:48px;border:1px solid #5f6368;background:#303134;color:#fff;border-radius:12px;font-weight:600}.mobile-tabs-count{color:#9aa0a6;font-size:12px}.mobile-tab-switcher-hidden{display:none!important}@media(min-width:701px){#mobileTabButton{display:none!important}}body.light .mobile-tabs-sheet{background:rgba(248,249,250,.96)}body.light .mobile-tab-card{background:#fff;border-color:#dadce0}.mobile-tabs-sheet button{touch-action:manipulation}`;
  document.head.appendChild(style);
  const button=document.createElement('button');button.id='mobileTabButton';button.type='button';button.setAttribute('aria-label','Show tabs');button.innerHTML='<span class="mobile-tab-count">1</span><span class="mobile-tab-icon">▢</span>';
  const toolbar=document.querySelector('.toolbar');toolbar?.insertBefore(button,document.getElementById('star'));
  const sheet=document.createElement('div');sheet.className='mobile-tabs-sheet mobile-tab-switcher-hidden';sheet.setAttribute('aria-label','Open tabs');sheet.innerHTML='<div class="mobile-tabs-head"><div><h2>Tabs</h2><span class="mobile-tabs-count">1 tab</span></div><button class="mobile-tabs-close" type="button" aria-label="Close tabs">×</button></div><div class="mobile-tabs-grid"></div><button class="mobile-tabs-new" type="button">+ New tab</button>';document.body.appendChild(sheet);
  const grid=sheet.querySelector('.mobile-tabs-grid'),count=sheet.querySelector('.mobile-tabs-count');
  const titleFor=t=>{const s=t.querySelector('span:nth-child(2)');return s?.textContent?.trim()||'Aither Web'};
  function refresh(){if(!isMobile())return;const all=[...document.querySelectorAll('#chromeTabs .tab')];button.querySelector('.mobile-tab-count').textContent=all.length;count.textContent=`${all.length} ${all.length===1?'tab':'tabs'}`;grid.innerHTML='';all.forEach(t=>{const card=document.createElement('button');card.type='button';card.className='mobile-tab-card'+(t.classList.contains('active')?' active':'');const title=titleFor(t);const id=t.id;const pageEl=document.getElementById(id+'Page')||document.getElementById(id==='aitherTab'?'homePage':'');const host=pageEl?.querySelector('.webview-toolbar span')?.textContent||'';card.innerHTML=`<div class="mobile-tab-preview">${id==='aitherTab'?'A':'▣'}</div><div class="mobile-tab-info"><span class="mobile-tab-title"></span><span class="mobile-tab-host"></span></div><button class="mobile-tab-x" type="button" aria-label="Close tab">×</button>`;card.querySelector('.mobile-tab-title').textContent=title;card.querySelector('.mobile-tab-host').textContent=host||'Aither Web';card.addEventListener('click',e=>{if(e.target.closest('.mobile-tab-x'))return;t.click();closeSheet()});card.querySelector('.mobile-tab-x').addEventListener('click',e=>{e.stopPropagation();t.querySelector('.tab-x')?.click();setTimeout(refresh,30)});grid.appendChild(card)});}
  function openSheet(){refresh();sheet.classList.remove('mobile-tab-switcher-hidden');document.body.style.overflow='hidden'}function closeSheet(){sheet.classList.add('mobile-tab-switcher-hidden');document.body.style.overflow=''}
  button.addEventListener('click',openSheet);sheet.querySelector('.mobile-tabs-close').addEventListener('click',closeSheet);sheet.querySelector('.mobile-tabs-new').addEventListener('click',()=>{document.getElementById('newTab')?.click();closeSheet()});
  new MutationObserver(()=>{if(!sheet.classList.contains('mobile-tab-switcher-hidden'))refresh()}).observe(tabsEl(),{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
  addEventListener('resize',()=>{if(!isMobile())closeSheet();refresh()});
  refresh();
})();
